/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ECOFORGE.VISTA;

/**
 *
 * @author YANFER
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        jLLogoEcoForge = new javax.swing.JLabel();
        jLIcono = new javax.swing.JLabel();
        jLInicioSesion = new javax.swing.JLabel();
        jLusuario = new javax.swing.JLabel();
        jLSeparador = new javax.swing.JSeparator();
        jTFNombreUsuario = new javax.swing.JTextField();
        jLContraseña = new javax.swing.JLabel();
        jLSeparador2 = new javax.swing.JSeparator();
        jPFContraseña = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        Fondo.setBackground(new java.awt.Color(255, 255, 255));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLLogoEcoForge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ECOFORGE/IMAGENES/ECOFORGE.jpg"))); // NOI18N
        Fondo.add(jLLogoEcoForge, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, -1, 500));

        jLIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ECOFORGE/IMAGENES/icono.png"))); // NOI18N
        Fondo.add(jLIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 50, 60));

        jLInicioSesion.setFont(new java.awt.Font("Roboto Bk", 0, 36)); // NOI18N
        jLInicioSesion.setText("INICIAR SESIÓN");
        Fondo.add(jLInicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 270, 60));

        jLusuario.setFont(new java.awt.Font("Roboto Lt", 1, 14)); // NOI18N
        jLusuario.setText("USUARIO");
        Fondo.add(jLusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 70, 30));
        Fondo.add(jLSeparador, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 270, 10));

        jTFNombreUsuario.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTFNombreUsuario.setForeground(new java.awt.Color(204, 204, 204));
        jTFNombreUsuario.setText("Ingrese su nombre de Usuario");
        jTFNombreUsuario.setBorder(null);
        Fondo.add(jTFNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 280, 30));

        jLContraseña.setFont(new java.awt.Font("Roboto Lt", 1, 14)); // NOI18N
        jLContraseña.setText("CONTRASEÑA");
        Fondo.add(jLContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 110, 30));
        Fondo.add(jLSeparador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 270, 10));

        jPFContraseña.setForeground(new java.awt.Color(204, 204, 204));
        jPFContraseña.setText("jPasswordField1");
        jPFContraseña.setBorder(null);
        Fondo.add(jPFContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 280, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fondo;
    private javax.swing.JLabel jLContraseña;
    private javax.swing.JLabel jLIcono;
    private javax.swing.JLabel jLInicioSesion;
    private javax.swing.JLabel jLLogoEcoForge;
    private javax.swing.JSeparator jLSeparador;
    private javax.swing.JSeparator jLSeparador2;
    private javax.swing.JLabel jLusuario;
    private javax.swing.JPasswordField jPFContraseña;
    private javax.swing.JTextField jTFNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
