/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ECOFORGE.VISTA;

import ECOFORGE.CONTROLADOR.ControladorCajaTexto;
import ECOFORGE.CONTROLADOR.ControladorLogin;
import ECOFORGE.CONTROLADOR.CrearCuotaEntidad;
import ECOFORGE.MODELO.CalculosDatos;
import ECOFORGE.MODELO.Cuota;
import ECOFORGE.MODELO.LoginUsuario;
import javax.swing.JOptionPane;

/**
 *
 * @author YANFER
 */
public class PanelCuota extends javax.swing.JPanel {

    /**
     * Creates new form PanelCuota
     */
    CrearCuotaEntidad crearCuota = null;
    CalculosDatos calculo = null;
    ControladorCajaTexto controladorCT = new ControladorCajaTexto();
    private final ControladorLogin controladorLogin;
    private CuotaAddedListener cuotaAddedListener;

    public PanelCuota() {
        initComponents();

        crearCuota = new CrearCuotaEntidad();

        calculo = new CalculosDatos();
        controladorLogin = ControladorLogin.obtenerInstancia();

        jcbCuotas.addItemListener(evt -> {
            if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
                Object selectedItem = jcbCuotas.getSelectedItem();
                if (selectedItem != null && !selectedItem.toString().equals("Seleccione...")) {
                    cargarValorCuota();
                } else {
                    jtfMontoCuota.setText(""); // Limpia el campo si no hay selección válida
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtfEstadoCuota = new javax.swing.JTextField();
        jtfIdVenta = new javax.swing.JTextField();
        jtfIdAsesor = new javax.swing.JTextField();
        jtfMontoCuota = new javax.swing.JTextField();
        jtfIdCuota = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jbtAgregar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jtfIntereses = new javax.swing.JTextField();
        jdcFechaVencimiento = new com.toedter.calendar.JDateChooser();
        jcbCuotas = new javax.swing.JComboBox<>();

        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(175, 229, 239));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(175, 229, 239));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Inserte datos de la cuota", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Roboto", 1, 24))); // NOI18N
        jPanel2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel2.setText("Número de Cuotas:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 170, -1));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setText("Numero Cuota:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 190, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel3.setText("Fecha Vencimiento:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 180, -1));

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel7.setText("Monto Cuota:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 180, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel4.setText("Estado Cuota:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 140, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel5.setText("Asesor:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 100, -1));

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel6.setText("Venta:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 170, -1));

        jtfEstadoCuota.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jtfEstadoCuota.setText("Pendiente");
        jtfEstadoCuota.setEnabled(false);
        jtfEstadoCuota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfEstadoCuotaKeyTyped(evt);
            }
        });
        jPanel2.add(jtfEstadoCuota, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 192, -1));

        jtfIdVenta.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jtfIdVenta.setEnabled(false);
        jtfIdVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfIdVentaKeyTyped(evt);
            }
        });
        jPanel2.add(jtfIdVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 192, -1));

        jtfIdAsesor.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jtfIdAsesor.setEnabled(false);
        jtfIdAsesor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfIdAsesorKeyTyped(evt);
            }
        });
        jPanel2.add(jtfIdAsesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 192, -1));

        jtfMontoCuota.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jtfMontoCuota.setEnabled(false);
        jtfMontoCuota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfMontoCuotaKeyTyped(evt);
            }
        });
        jPanel2.add(jtfMontoCuota, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 192, -1));

        jtfIdCuota.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jtfIdCuota.setText("1");
        jtfIdCuota.setEnabled(false);
        jtfIdCuota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfIdCuotaKeyTyped(evt);
            }
        });
        jPanel2.add(jtfIdCuota, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 192, -1));

        jPanel3.setBackground(new java.awt.Color(193, 65, 62));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jbtAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ECOFORGE/IMAGENES/Agregar_30.png"))); // NOI18N
        jbtAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtAgregar.setLabel("AGREGAR");
        jbtAgregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jbtAgregar)
                .addContainerGap(162, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 390, 70));

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel8.setText("Intereses:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 170, -1));

        jtfIntereses.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jtfIntereses.setText("4");
        jtfIntereses.setEnabled(false);
        jtfIntereses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfInteresesActionPerformed(evt);
            }
        });
        jtfIntereses.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfInteresesKeyTyped(evt);
            }
        });
        jPanel2.add(jtfIntereses, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 192, -1));
        jPanel2.add(jdcFechaVencimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 190, -1));

        jcbCuotas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "2", "4", "6", "8", "10" }));
        jPanel2.add(jcbCuotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 190, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 410, 450));

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void jtfEstadoCuotaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfEstadoCuotaKeyTyped
        // controladorCT.longitudCaracter(jtfDireccion, 50, evt);
    }//GEN-LAST:event_jtfEstadoCuotaKeyTyped

    private void jtfIdVentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfIdVentaKeyTyped
        //controladorCT.longitudCaracter(jtfCorreoElectronico, 30, evt);
    }//GEN-LAST:event_jtfIdVentaKeyTyped

    private void jtfIdAsesorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfIdAsesorKeyTyped
        // controladorCT.soloNumeros(evt);
        //controladorCT.longitudCaracter(jtfTelefono, 10, evt);
    }//GEN-LAST:event_jtfIdAsesorKeyTyped

    private void jtfMontoCuotaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfMontoCuotaKeyTyped
        // controladorCT.soloNumeros(evt);
        //controladorCT.longitudCaracter(jtfSubsidio_Ministerio, 7, evt);
    }//GEN-LAST:event_jtfMontoCuotaKeyTyped

    private void jtfIdCuotaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfIdCuotaKeyTyped
        //controladorCT.soloNumeros(evt);
        //controladorCT.longitudCaracter(jtfIdCuota, 10, evt);
    }//GEN-LAST:event_jtfIdCuotaKeyTyped

    private void jbtAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAgregarActionPerformed

        // Obtener datos de los campos de texto
        Integer id_Venta = Integer.valueOf(jtfIdVenta.getText());

        java.util.Date utilDate = jdcFechaVencimiento.getDate(); // Obtener la fecha como java.util.Date
        java.sql.Date fecha_vencimiento = null;

        // Verificar si la fecha no es nula antes de la conversión
        if (utilDate != null) {
            fecha_vencimiento = new java.sql.Date(utilDate.getTime());
        }

        Integer monto_Cuota = Integer.valueOf(jtfMontoCuota.getText());
        String estado_Cuota = jtfEstadoCuota.getText();
        String numero_Asesor = jtfIdAsesor.getText();
        Integer intereses = Integer.valueOf(jtfIntereses.getText());
        Integer numero_Cuotas = Integer.valueOf((String) jcbCuotas.getSelectedItem());

        // Crear un objeto Cliente
        Cuota nuevaCuota = new Cuota(1, 1, fecha_vencimiento, monto_Cuota, estado_Cuota, numero_Asesor, intereses, id_Venta, numero_Cuotas);

        // Agregar cliente utilizando el controlador
        if (crearCuota.armarCrud().Crear(nuevaCuota)) {
            JOptionPane.showMessageDialog(this, "Cuotas agregadas exitosamente.");
            // Notificar al listener que se ha agregado un cliente
            if (cuotaAddedListener != null) {
                cuotaAddedListener.onCuotaAdded();
                System.out.print("Terminó");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Error al agregar Cuotas.");
        }
    }//GEN-LAST:event_jbtAgregarActionPerformed

    private void jtfInteresesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfInteresesKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfInteresesKeyTyped

    private void jtfInteresesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfInteresesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfInteresesActionPerformed

    void cargarIdVenta(String numero_Venta) {
        jtfIdVenta.setText(numero_Venta);
    }

    void cargarIdAsesor() {
        LoginUsuario usuarioActivo = controladorLogin.getUsuarioActivo();
        if (usuarioActivo != null) {
            jtfIdAsesor.setText(usuarioActivo.getID_USUARIO()); // Suponiendo que LoginUsuario tiene el método getIdUsuario
        } else {
            jtfIdAsesor.setText("No hay usuario activo.");
        }
    }

    public void cargarValorCuota() {
        Integer idVenta = Integer.valueOf(jtfIdVenta.getText());
        Integer numeroCuotas = Integer.valueOf((String) jcbCuotas.getSelectedItem());
        double intereses = Integer.parseInt(jtfIntereses.getText());
        if (idVenta != null && numeroCuotas > 0 && intereses > 0) {
            Integer valor_Total = calculo.CalcularValorCuota(idVenta, numeroCuotas, intereses);
            jtfMontoCuota.setText(String.valueOf(valor_Total));
        }
    }

    public interface CuotaAddedListener {

        void onCuotaAdded();
    }
    
    public void setCuotaAddedListener(CuotaAddedListener listener) {
        this.cuotaAddedListener = listener;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbtAgregar;
    private javax.swing.JComboBox<String> jcbCuotas;
    private com.toedter.calendar.JDateChooser jdcFechaVencimiento;
    private javax.swing.JTextField jtfEstadoCuota;
    private javax.swing.JTextField jtfIdAsesor;
    public javax.swing.JTextField jtfIdCuota;
    private javax.swing.JTextField jtfIdVenta;
    private javax.swing.JTextField jtfIntereses;
    private javax.swing.JTextField jtfMontoCuota;
    // End of variables declaration//GEN-END:variables
}
