/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ECOFORGE.VISTA;
import ECOFORGE.CONTROLADOR.ControladorCajaTexto;
import ECOFORGE.CONTROLADOR.ControladorVistaTorreProyecto;
/**
 *
 * @author YANFER
 */
import ECOFORGE.CONTROLADOR.ControladorProyecto;
import ECOFORGE.CONTROLADOR.ControladorUtilidades;
import ECOFORGE.MODELO.Proyecto;
import javax.swing.JOptionPane;

public class ProyectoVista extends javax.swing.JFrame {

    private ControladorProyecto controlador;
    private boolean isModoActualizar = false;
    private datosProyectosVista formularioProyecto;
    ControladorCajaTexto controladorCT = new ControladorCajaTexto();
    private ControladorVistaTorreProyecto controladorr;    
    

    /**
     * Creates new form datosProyecto
     */
    public ProyectoVista(datosProyectosVista formularioProyecto) {
        initComponents();
        this.formularioProyecto = formularioProyecto;
        controlador = new ControladorProyecto();
        configurarFormulario();
        controladorr = new  ControladorVistaTorreProyecto(this);
        ControladorUtilidades.centrarVentana(this);
    }
    
    public String getCodigoProyecto(){
        return  jTextFieldCodProyecto.getText();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        btnEcharAtras = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jTextFieldCodProyecto = new javax.swing.JTextField();
        jTextFieldNombreProyecto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnActualizar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Datos del Cliente");
        setLocationByPlatform(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(108, 93, 71));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Creando proyecto ");

        btnCerrarSesion.setBackground(new java.awt.Color(255, 188, 71));
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        btnEcharAtras.setBackground(new java.awt.Color(255, 188, 71));
        btnEcharAtras.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEcharAtras.setText("Atrás");
        btnEcharAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEcharAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEcharAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(btnCerrarSesion)
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEcharAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 50));

        jPanel5.setBackground(new java.awt.Color(175, 229, 239));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldCodProyecto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCodProyectoKeyTyped(evt);
            }
        });
        jPanel5.add(jTextFieldCodProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 190, 30));

        jTextFieldNombreProyecto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNombreProyectoKeyTyped(evt);
            }
        });
        jPanel5.add(jTextFieldNombreProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 190, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Codigo");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 60, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Nombre");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 102, 20));

        jPanel6.setBackground(new java.awt.Color(193, 65, 62));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel6.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 100, 40));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        btnGuardar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btnGuardarKeyTyped(evt);
            }
        });
        jPanel6.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 90, 40));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 510, 70));

        jPanel1.setBackground(new java.awt.Color(175, 229, 239));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 226, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 166, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 230, 170));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 510, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // Obtener datos de los campos de texto
        String codigo_proyecto = jTextFieldCodProyecto.getText();
        String nombre_proyecto = jTextFieldNombreProyecto.getText();
        

        // Crear un objeto Proyecto
        Proyecto nuevoProyecto = new Proyecto(codigo_proyecto, nombre_proyecto);

        // Agregar Proyecto utilizando el controlador
        if (controlador.crearProyecto(nuevoProyecto)) {
            JOptionPane.showMessageDialog(this, "Proyecto agregado exitosamente.");

            
            // Actualizar la tabla en el formulario Proyecto
            formularioProyecto.actualizarTabla();
            datosProyectosVista datosProyectos = new datosProyectosVista();
            datosProyectos.setVisible(true); 

            this.dispose(); // Cerrar el formulario
        } else {
            JOptionPane.showMessageDialog(this, "Error al agregar Proyecto.");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        if (isModoActualizar) {
            // Código para actualizar el Proyecto
            String codigo_proyecto = jTextFieldCodProyecto.getText();
            String nombre_proyecto = jTextFieldNombreProyecto.getText();
            Proyecto actualizarProyecto = new Proyecto(codigo_proyecto, nombre_proyecto);
            // Llamar al controlador para actualizar
            if (controlador.actualizarProyecto(actualizarProyecto)) {
                JOptionPane.showMessageDialog(this, "Proyecto actualizado correctamente.");
                // Cerrar el formulario después de actualizar
                formularioProyecto.actualizarTabla();
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Error al actualizar el Proyecto.");
            }
        } else {
            // Código para agregar un nuevo Proyecto
            // (Ya lo tienes implementado)
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        Login newframe = new Login();
        newframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnEcharAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEcharAtrasActionPerformed
        datosProyectosVista newframe = new datosProyectosVista();
        newframe.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnEcharAtrasActionPerformed

    private void jTextFieldNombreProyectoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreProyectoKeyTyped
        controladorCT.soloLetras(evt);
    }//GEN-LAST:event_jTextFieldNombreProyectoKeyTyped

    private void jTextFieldCodProyectoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCodProyectoKeyTyped
        
    }//GEN-LAST:event_jTextFieldCodProyectoKeyTyped

    private void btnGuardarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnGuardarKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarKeyTyped
    public void cargarDatos(Integer codigo_proyecto, String nombre_proyecto) {
        jTextFieldCodProyecto.setText(String.valueOf(codigo_proyecto));
        jTextFieldNombreProyecto.setText(nombre_proyecto);

        // Deshabilitar la caja de texto de cédula para que no sea modificable
        jTextFieldCodProyecto.setEnabled(false);
    }

    public void setModoActualizar(boolean modoActualizar) {
        this.isModoActualizar = modoActualizar;
    }
    
    private void configurarFormulario() {
        // jButton2.setEnabled(true); // Desactivar el botón de Actualizar
        // jButton1.setEnabled(true);     // Activar el botón de Agregar
        if (isModoActualizar) {
            btnActualizar.setEnabled(true);  // Activar el botón de Actualizar
            btnGuardar.setEnabled(false);    // Desactivar el botón de Agregar
        } else {
            btnActualizar.setEnabled(false); // Desactivar el botón de Actualizar
            btnGuardar.setEnabled(true);     // Activar el botón de Agregar
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProyectoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProyectoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProyectoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProyectoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProyectoVista(new datosProyectosVista()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnEcharAtras;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jTextFieldCodProyecto;
    private javax.swing.JTextField jTextFieldNombreProyecto;
    // End of variables declaration//GEN-END:variables
}
